### ISSUE TITLE
бот не отвечает

### ISSUE THREAD

**Issue by AlexanderKozhevin** [AsakoKabe/pseudo-kant#1]
<img width="951" alt="Screenshot 2021-07-13 at 08 37 52" src="https://user-images.githubusercontent.com/4464561/125396743-9dbe1d00-e3b5-11eb-9fb3-e4ccb69a731c.png">

**Comment by AsakoKabe** [comment]
Я отключил бота на сервере. Добавлю эту информацию в README. 
Спасибо, что оставили issue.
